day1/homework/car_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from car_inventory.models import User,db, check_password_hash
from car_inventory.forms import UserLoginForm
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint("auth", __name__, template_folder="auth_templates")

@auth.route("/signup", methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully created a user account, {email}", "user-created")

            return redirect(url_for('site.index'))
    except:
        raise Exception("Invalid Form Data: Please Check your form")
    return render_template("signup.html", form=form)

@auth.route("/signin", methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash("You were successfullt loggin in: via Email/Password", "auth-success")
                return redirect(url_for("site.profile"))
            else:
                flash("Your Email/Password is incorrect! Try Again!", "auth-failed")
                return redirect(url_for("auth.signin"))
    except:
        raise Exception("Invalid Form Data: Please Check Your Form!")
    return render_template("signin.html", form=form)

@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("site.index"))

day1/homework/car_inventory/site/routes.py
from flask import Blueprint, render_template

site = Blueprint("site", __name__, template_folder="site_templates")

@site.route("/")
def index():
    return render_template("index.html")

@site.route("/profile")
def profile():
    return render_template("profile.html")

day1/homework/car_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="Description" content="Enter your description here"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
        <link rel="stylesheet" href="../static/css/main.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
        <title>Car Inventory</title>
    </head>
    <body>
        <nav class="ct-nav">
            <div>
                <img src="../static/images/car.png" alt="Car Company Logo">
            </div>
            <div>
                <ul id="horizontal-list">
                    <a href="{{ url_for('site.index') }}">
                        <li>Car Inventory Home</li>
                    </a>
                    <a href="">
                        <li>Donate</li>
                    </a>
                    <a href="{{ url_for('site.profile') }}">
                        <li>Profile</li>
                    </a>
                    {% if current_user.isauthenticated %}
                    <a href="{{ url_for('auth.logout') }}">
                        <li>Log Out</li>
                    </a>
                    {% else %}
                    <a href="{{ url_for('auth.signin') }}">
                        <li>Sign In</li>
                    </a>
                    <a href="{{ url_for('auth.signup') }}">
                        <li>Sign Up Free</li>
                    </a>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
        <div class="container">
            <footer class="row" id="footer">
                <div class="col-2 col-md-2">
                    <img src="../../static/images/car.svg" alt="Car Company Logo" id="footer-logo">
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Platform</h4>
                        <p>Why cars?</p>
                        <p>Car Inventory Link</p>
                        <p>Donate</p>
                        <p>Spread a Disease</p>
                        <p>Our Process</p>
                    </div>
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Platform</h4>
                        <p>Dabble in illegal finances</p>
                        <p>Fake your death</p>
                        <p>Move across the world</p>
                        <p>????</p>
                        <p>Profit</p>
                    </div>
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Platform</h4>
                        <p>a Haiku</p>
                        <p>spaghetti</p>
                        <p>Italian food</p>
                        <p>mac and cheese</p>
                        <p>... so beautiful</p>
                    </div>
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Platform</h4>
                        <p>Car stuff</p>
                        <p>The Car Project</p>
                        <p>Invest and not get anything back</p>
                        <p>Spread The Mayo</p>
                        <p>Our Process</p>
                    </div>
                </div>
                <div class="col-2 col-md-2">
                    <div class="footer-text-flex">
                        <h4>Platform</h4>
                        <p>Car stuff</p>
                        <p>The Car Project</p>
                        <p>Invest and not get anything back</p>
                        <p>Spread The Mayo</p>
                        <p>Our Process</p>
                    </div>
                </div>
            </footer>
        </div>
    </body>
</html>

day1/homework/car_inventory/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here: ") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here: ") }}
        </fieldset>
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>